List:
    type: object
    config:
        description: "An List"
        fields:
            id:
                type: "ID!"
                description: "The unique ID of the list."
                access: "@=hasRole('ROLE_USER')"
            tag:
                type: "String!"
                access: "@=hasRole('ROLE_USER')"
            label:
                type: "String!"
                access: "@=hasRole('ROLE_USER')"
            value:
                type: "String!"
                access: "@=hasRole('ROLE_USER')"