Token:
    type: object
    config:
        description: "An Token"
        fields:
            user:
                type: "User"
            token:
                type: "String!"

TokenList:
  type: object
  config:
    description: "A list of Token"
    fields:
      tokens:
        type: "[Token]"
        description: "Tokens"