Mutation:
  type: "object"
  config:
    fields:
      signin:
        type: "Token"
        args:
          crendentials:
            type: "App\\GraphQL\\Type\\Input\\LoginInput!"
        resolve: "@=mutation('login', [args['crendentials']])"
        description: "signin"
      token_new:
        type: "Token"
        args:
          token:
            type: "App\\GraphQL\\Type\\Input\\UserUuidInput!"
        resolve: "@=mutation('tokenNew', [args['token']])"
        description: "Add new Token API."