Query:
    type: "object"
    config:
        description: "User ORM repository"
        fields:
            userAuth:
                type: "User"
                resolve: "@=resolver('UserAuth')"