Query:
    type: "object"
    config:
        description: "User ORM repository"
        fields:
            userAuth:
                type: "User"
                resolve: "@=resolver('UserAuth')"
            listList:
                type: "ListList"
                args:
                    tag:
                        description: "Tag"
                        type: "String"
                    first:
                        description: "First"
                        type: "Int"
                    offset:
                        description: "offset"
                        type: "Int"
                    limit:
                        description: "limit"
                        type: "Int"
                resolve: "@=resolver('ListList', [args])"