Token:
    type: object
    config:
        description: "An Token"
        fields:
            user:
                type: "User"
            token:
                type: "String!"
            type:
                type: "String!"
            expired:
                type: "Boolean!"